---
apiVersion: v1
kind: Namespace
metadata:
  name: chess
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chess  # Application name is now 'chess'
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sujeetrepublicworld/test-app.git
    targetRevision: HEAD
    path: deploy  # Only 'deploy' folder
  destination:
    server: https://kubernetes.default.svc
    namespace: chess-game  # Namespace is 'chess'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
