apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-app-tls
  namespace: default
spec:
  secretName: test-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sujeetkushwaha.shop
  dnsNames:
    - sujeetkushwaha.shop
